### ISSUE TITLE
Bot not dropping battle machine or CC troops

### ISSUE THREAD

**Issue by Xpl0itU** [xbebenk/MBR_xbebenkMod#101]
It does drop CC spells

Using latest dev version

The drops are in the CSV I’m using

**Comment by xbebenk** [comment]
too few info...
battle machine is on Builderbase, and CC troops is on main village
can you clarify ?

**Comment by Xpl0itU** [comment]
Sorry, it doesn’t drop sieges, I’m using the CSV ElectroLoon by Leandro v1.2

**Comment by xbebenk** [comment]
please enable this debug:
![image](https://user-images.githubusercontent.com/6594360/216544314-fa765843-50ac-4a40-9f7d-e55d1288a9b4.png)

also please send your attack setting:
![image](https://user-images.githubusercontent.com/6594360/216544493-09410f09-737d-41ca-862d-6b9d5eccaca1.png)

and your csv file

**Comment by Xpl0itU** [comment]
![image](https://user-images.githubusercontent.com/24777100/216649940-a23ecece-6012-47e4-a83b-480a73351743.png)

**Comment by Xpl0itU** [comment]
After enabling the debug options you mention, it started dropping the sieges, can’t confirm about the CC, but will do soon

**Comment by Xpl0itU** [comment]
It does indeed drop CC and sieges too

**Comment by Xpl0itU** [comment]
Now it doesn’t drop them again

**Comment by xbebenk** [comment]
try use Any Siege option:
![image](https://user-images.githubusercontent.com/6594360/219305010-700f70ef-1d14-44a2-9167-bf9893a6692d.png)

on your csv:
![image](https://user-images.githubusercontent.com/6594360/219305177-1ce37fe6-4b25-4bac-850b-248c3eb1f3fc.png)
only Clan Castle, Wall Wrecker, Battle Blimp and Stone Slammer can be dropped

please send csv attack log when problem occur again

**Comment by Xpl0itU** [comment]
[debugAttackCSV.log](https://github.com/xbebenk/MBR_xbebenkMod/files/10767961/debugAttackCSV.log)
Found the debug log, still only dropping spells only from time to time but not troops or sieges

**Comment by xbebenk** [comment]
![image](https://user-images.githubusercontent.com/6594360/219691455-6c73fd8c-e3e4-41d9-b55d-74d5a55f5b3e.png)
from log it should drop Wall Wrecker
can you send normal bot log on that time?

**Comment by Xpl0itU** [comment]
Couldn't upload it to github, so here it is [https://we.tl/t-qbPvFs9clb](https://we.tl/t-qbPvFs9clb)
