### ISSUE TITLE
User Input Error on Profile Switch

### ISSUE THREAD

**Issue by john-sp** [xbebenk/MBR_xbebenkMod#105]
I have multiple profiles that I use for multiple accounts using account switcher, but when I try to open up the second profile (or 3rd) via the switch profiles dropdown it always gives this error and I have to kill the script via Task Manager. I am on the most recent beta ([af6927d](https://github.com/xbebenk/MBR_xbebenkMod/commit/af6927d82a520cd73d476ef818f953969f4b96a0)). Let me know what logs you need!

![image](https://user-images.githubusercontent.com/20563885/236654551-c37dcfce-78de-4c84-9a63-6d9ba91743e2.png)

**Comment by xbebenk** [comment]
you need to learn how to set account switch
please read the how to on forum

**Comment by john-sp** [comment]
I believe that I did set account switch correct as I have set up 8.0.2 in the meantime and it works. Just changing profiles has this error, even if I have account switch turned off

**Comment by xbebenk** [comment]
im so sorry that i cannot really maintain the bot
also too few info you provide
if you have no problem with 8.0.2 then i suggest you keep using it

**Comment by john-sp** [comment]
Issue fixed by not having the profile name end in a number
