### ISSUE TITLE
CleanYard doesn't work on main village

### ISSUE THREAD

**Issue by JustGuardian** [xbebenk/MBR_xbebenkMod#106]
The function cleanYard() doesn't work on the main village, althought it works in the builderbase village. It would be useful also if it could remove only the "common" obstacles (like trees, trunks, bushes) while leaving the rare obstacles.

**Comment by xbebenk** [comment]
just run fine on mine
using dev branch

**Comment by JustGuardian** [comment]
I am also running dev_1.2.4 branch, and I have 7 accounts. In none of them it removes the obstacles in the main village. How can I help you understand what's not working?

**Comment by NothingJustBlank** [comment]
Please post the .png taken from the bot

**Comment by JustGuardian** [comment]
How do I enable the bot to output it? In the debug session which option do I have to select?

**Comment by xbebenk** [comment]
![image](https://user-images.githubusercontent.com/6594360/237012577-3c476c4e-1cb1-4224-8385-248d8f91beab.png)

just run fine on mine
make sure you enable this
![image](https://user-images.githubusercontent.com/6594360/237013018-011883ff-a6ee-4f7a-b699-607698343147.png)

**Comment by JustGuardian** [comment]
done it, same result sadly.

**Comment by NothingJustBlank** [comment]
Please make a proper bug report by at least providing logs, screenshot of the problem (in this case your village)

**Comment by JustGuardian** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/70069888/05b97ea3-0f32-40bc-a030-a5a2dc42fe1c)
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/70069888/2a905417-e086-430b-a31d-9fb229063d48)
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/70069888/554a7ff1-18aa-46cc-bc0a-4b45709cd27b)

**Comment by xbebenk** [comment]
Stop Bot
paste this line to debug textbox, and run

QuickMIS("CNX", $g_sImgCleanYard, 20,20,840,630)
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/9ce41ed0-a818-4e7e-8089-392e31e6dff1)

**Comment by JustGuardian** [comment]
Using `QuickMIS("CNX", $g_sImgCleanYard, 20,20,840,630)` it detects some obstacles. Now I try cleaning the yard using the debug option.

**Comment by JustGuardian** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/70069888/3ce27e2f-c461-49c0-8f91-3faa8fc2279a)
are those obstacles not considered?
