### ISSUE TITLE
Purge BB events in clan games

### ISSUE THREAD

**Issue by devreagi** [xbebenk/MBR_xbebenkMod#110]
I have the option "Force Do Only BuilderBase Event" activated, but the bot purges even those events.

![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/69402757/cf904232-3665-42e4-9da3-58bde34160a8)

Maybe some misconfiguration on my part?

![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/69402757/a0da2b4a-6eb8-4ed3-8a0b-5472920d2c2a)

**Comment by NothingJustBlank** [comment]
no support for BB atm, therefore no support for bb clangames. good luck!
