### ISSUE TITLE
DE Village Report & Upgrade Heroes

### ISSUE THREAD

**Issue by Jonas-VN** [xbebenk/MBR_xbebenkMod#112]
When using WINAPI as the Screencapture Background Mode the bot is able to detect the pixel that I have an elixir storage, but when using ADB screencap it isn't able to detect that pixel (It finds a color that is just a few pixels to the side of it).

<details>
<summary>WINAPI log:</summary>

[19:36:03] Run Function : VillageReport()
[19:36:04] Village Report
[19:36:04]  [T]: 2 572
[19:36:04]  [G]: 14 337 170 [E]: 15 585 753 [D]: 257 172 [GEM]: 2 226
[19:36:04] Result : 0
[19:36:04] [984ms]
</details>

<details>
<summary>ADB screencap log:</summary>

[19:36:22] Run Function : VillageReport()
[19:36:22] Village Report
[19:36:22]  [T]: 2 572
[19:36:23]  [G]: 14 337 170 [E]: 15 585 753 [GEM]: 257 172
[19:36:23] Result : 0
[19:36:23] [906ms]
</details>

Also when trying to upgrade a hero it never finds the white zeros that are used to confirm the upgrade. It always logs "Champion Upgrade Fail! No DE!" eventhough I have enough DE and the zeros are white. (This was done when the DE was properly detected, so the first issue isn't related)

Tried reinstalling the bot & BS5 Pie without success.
Current BS5 Pie version: 5.12.0.1085
Old BS5 Pie version (with the same issues): 5.11.?.????

**Comment by xbebenk** [comment]
Nice catch 👍 

i am using BS 5.11.100.1063 and 5.11.11.1002 
Both have same issue:
If using adb screencap, captured image are shifted 1 pixel to right

using adb screencap:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/212b86e5-9055-42da-acef-51c3dd53aac8)

using directx:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/6059d6ad-0ebd-497f-9cfe-9dff7b6dc915)


workaround : use another location which not affected by this shifting

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/08e55912-6a3b-45e9-9fbd-1c053dfeeb85)

**Comment by Jonas-VN** [comment]
Fixed, thanks!

Regarding the issue about upgrading heroes, changing \imgxml\Main Village\Upgrade\WhiteZero_0_92.xml to \imgxml\Main Village\Upgrade\WhiteZero_0_87.xml fixed that for me (only tested with King, Queen and Royal Champion. Don't have a Grand Warden available to test atm).

**Comment by xbebenk** [comment]
i personally never use upgrade heroes tab settings
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/0f77ff99-d602-440d-adda-e2b3905a903d)

i just let auto upgrade do it
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/4de3cba7-03c1-4bfe-b642-c9b1d8ab4b25)

**Comment by Jonas-VN** [comment]
That does work, thanks!
