### ISSUE TITLE
Unable to find next button on search

### ISSUE THREAD

**Issue by nico1223** [xbebenk/MBR_xbebenkMod#114]
This is only happens on my th13 account. The bot is able to search for bases on my th6,7,8 accounts. 

**Bug:**

The bot loads the base, goes to find a village to attack, once the first village loads, gets the loot data, and then keep waiting to find the next button without actually clicking it.

I have some screenshots and debug images.

### First search

![QuickMIS_BC109 06 2023 at 05 22 39](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/5d70918a-3e8a-4333-9582-d9b3bb1190d5)

![Screenshot_6](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/b665e73f-1b25-4274-b168-caef02d1c82d)

### Second search

![QuickMIS_BC109 06 2023 at 05 49 26](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/52efb68e-de0b-4f46-96e6-20110098fdbf)

![Screenshot_10](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/d071843e-3b5d-4f57-b108-1863a20fd198)

Debug images are from \Temp\Debug\QuickMIS_BC1

**Comment by xbebenk** [comment]
Try this:
1. stop bot
2. go to search manually
3. go to debug tab, put this on run function text box: _GetPixelColor($NextBtn[0], $NextBtn[1], True)
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/a3790e35-d926-47e2-93dc-94a32b11ed78)
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/5aa5f0cd-1e38-4002-8a42-c8e82c080399)

what result you got?

**Comment by nico1223** [comment]
I got 632E0D multiple times on different attack villages

![Screenshot_11](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/059e6b25-7bed-40b7-8c25-e46b710c90ef)

**Comment by nico1223** [comment]
on a th6 where searching bases work, I got E5590D

- same blustack instance
- same mbr version

![Screenshot_12](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/a27d3999-5ba6-4832-b4ee-1f867bfabfa5)

**Comment by xbebenk** [comment]
please load again the not work account
goto search, take screenshot from photo button

**Comment by nico1223** [comment]
![2023-06-09_07 39 07](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/044a0c0b-403a-44be-a2a7-9cf190114440)

**Comment by xbebenk** [comment]
This is from your image:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/540925a6-624a-4dba-bce4-8830b7320571)

**Comment by xbebenk** [comment]
and this is from mine:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/7151add5-75d4-4ea3-b212-ad9859733b3a)

**Comment by xbebenk** [comment]
position of next button are different, on yours it slightly lower, and make this colorchek failed
are you sure you are using same instance?
what are your BS5 version and coc version?

BS version im using = 5.11.11.1002 and 5.11.100.1063
coc version = 15.292.14

**Comment by nico1223** [comment]
Thank you for the reply. Yes, it's the same instance and the same coc version. I switch using the switch profile button on mbr.

- COC version: 15.292.17
- BS version: 15.12.0.1085

Here's an image from where the next button do work:

![2023-06-09_08 13 12](https://github.com/xbebenk/MBR_xbebenkMod/assets/96672685/87c7ef12-e48e-4e50-97d7-f09fa2144645)

**Comment by nico1223** [comment]
after your comment, I removed the profile from mbr and loaded the data for it from a fresh install of coc. 

I think that fixed the issue. Not extactly sure why the location of the button would change when all the accounts were using the same coc version.

I'll test this new profile for a few hours and see if I run into the issue again. 

Thank you for your help ^^

**Comment by nico1223** [comment]
reloading shared_pref data solved the issue
