### ISSUE TITLE
Adjusted to be able to do 2 attacks in BB2

### ISSUE THREAD

**Issue by Hoith95** [xbebenk/MBR_xbebenkMod#115]
; Adjusted to be able to do 2 attacks in BB2

		$sTmpDamage = Number($sDamage)
		If $bCountSameDamage > 5 Then 
			If $g_bDebugSetLog Then SetLog("AttackBB Loop: No Change on Overall Damage, Exit!", $COLOR_ERROR)
			AttackBB(True)
			ExitLoop
		EndIf
		
		If $g_bDebugSetLog Then SetLog("Waiting Battle End #" & $waitcount, $COLOR_ACTION)
		If _Sleep(2600) Then Return
		If IsProblemAffect(True) Then Return
		If Not $g_bRunState Then Return
		$waitcount += 1
		If $waitcount > 30 Then ExitLoop
	Wend
	Return
EndFunc   ;==>AttackBB

; Optimized to improve the ability to deploy missed soldiers

If $isBlueBanner Or $isVioletBanner Then
					$Troop =  $g_iQuickMISName
					$Troopy = $iSelectTroopY
					If Not $bTest Then $iCount = Number(getOcrAndCapture("coc-tbb", $ColorPickBannerX, $iTroopBanners - 12, 35, 28, True))
					If $isVioletBanner Then $iCount = 5
					
					Local $aTempElement[1][5] = [[$Troop, $Troopx, $Troopy, $k, $iCount]] ; element to add to attack bar list
					_ArrayAdd($aBBAttackBar, $aTempElement)
				EndIf
			EndIf
		Else
			If $g_bDebugSetlog Then SetLog("Slot [" & $k & "]: isBlueBanner=" & String($isBlueBanner) & " isVioletBanner=" & String($isVioletBanner), $COLOR_DEBUG2)
			If QuickMIS("BC1", $g_sImgDirBBTroops, $Troopx, $iTroopBanners, $Troopx + 73, 670) Then 
				If $g_bDebugSetlog Then SetLog("Slot [" & $k & "]: TroopBanner ColorpickY=" & $ColorPickBannerX, $COLOR_DEBUG2)
				$isVioletBanner = _ColorCheck(_GetPixelColor($ColorPickBannerX, $iTroopBanners, True), Hex(0xC434FC, 6), 30) ; Violet Banner on TroopSlot = TroopSlot Quantity = 1 
				$isBlueBanner = _ColorCheck(_GetPixelColor($ColorPickBannerX, $iTroopBanners, True), Hex(0x3874FF, 6), 30) ; Blue Banner on TroopSlot = TroopSlot Quantity > 1 
				
				$bReadTroop = $isBlueBanner Or $isVioletBanner
				If $bTest Then $bReadTroop = True
				If $bReadTroop Then
					$Troop =  $g_iQuickMISName
					$Troopy = $iSelectTroopY
					If Not $bTest Then $iCount = Number(getOcrAndCapture("coc-tbb", $ColorPickBannerX, $iTroopBanners - 12, 35, 28, True))
					If $isVioletBanner Then $iCount = 1
; Tuned so Nox can run
Global $g_bAndroidAdbUseMyBot = True ; Use MyBot provided adb.exe and not the one from emulator
; Overall, there are still errors, please help more.

![Screenshot 2023-06-10 075850](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/bb96c464-658f-4e63-902c-cb5987aba276)
![Screenshot 2023-06-10 075920](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/1ea7ba39-5ffb-4e8b-8ffa-34da6f723734)

**Comment by NothingJustBlank** [comment]
2 attacks in BB is not possible currently, we do not have the redline to act as reference for drop points.
We turned off mybot adb as it has some issues with the new version of android.
Most of our community run under BS5, it is more lightweight compared to Nox.
