### ISSUE TITLE
Try secondary village measuring.. 

### ISSUE THREAD

**Issue by KDB19** [xbebenk/MBR_xbebenkMod#120]
#I have the latest version of xbebenk and pie64 bit bluestacks
But I get this message 
 Try secondary village measuring...
 https://i.imgur.com/iouxa5Y.png
Use bluestacks version 5.11.100.1063
Is there anything i can do? Please Help

**Comment by xbebenk** [comment]
use normal scenery,
enable debug message
run function ZoomOut()

**Comment by KDB19** [comment]
And it restarts the bot
And he does the same thing over and over again

**Comment by xbebenk** [comment]
send your log located under profile/log folder

**Comment by KDB19** [comment]
https://i.imgur.com/BMsQYaI.png 
I do not like to disturb you, but I have no experience, do you mean this?

**Comment by KDB19** [comment]
https://www.mediafire.com/file/hctacqfd18dqvb6/Logs.rar/file 
Good ?

**Comment by KDB19** [comment]
2: D [2023-06-13 17:26:03.081] Created log file: M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\Profiles\MyVillage\Logs\2023-06-13_17.26.03.log
2: D [2023-06-13 17:26:03.082] Android: BlueStacks5
2: D [2023-06-13 17:26:03.083] Android Instance: Pie64
2: D [2023-06-13 17:26:03.084] Android Version: 5.12.0.1085
2: D [2023-06-13 17:26:03.085] Android Version API: 28
2: D [2023-06-13 17:26:03.085] Android ADB Device: 127.0.0.1:5555
2: D [2023-06-13 17:26:03.086] Android Program Path: C:\Program Files\BlueStacks_nxt\HD-Player.exe
2: D [2023-06-13 17:26:03.087] Android Program FileVersionInfo: 1033,,BlueStack Systems,BlueStacks,5.12.0.1085,,Copyright 2011 BlueStack Systems, Inc.  All Rights Reserved.,,HD-Player,BlueStacks,5.12.0.1085,,
2: D [2023-06-13 17:26:03.088] Android ADB Path: C:\Program Files\BlueStacks_nxt\HD-Adb.exe
2: D [2023-06-13 17:26:03.089] Android ADB Global Options: 
2: D [2023-06-13 17:26:03.090] Android VBoxManage Path: C:\Program Files\BlueStacks_nxt\BstkVMMgr.exe
2: D [2023-06-13 17:26:03.091] Android ADB Shared Folder: /mnt/windows/BstSharedFolder/
2: D [2023-06-13 17:26:03.092] Full Command Line: 0
2: D [2023-06-13 17:26:03.093] @AutoItExe: C:\Program Files (x86)\AutoIt3\AutoIt3.exe
2: D [2023-06-13 17:26:03.094] @ScriptFullPath: M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\MyBot.run.au3
2: D [2023-06-13 17:26:03.095] @WorkingDir: M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\lib
2: D [2023-06-13 17:26:03.096] @AutoItPID: 10076
2: D [2023-06-13 17:26:03.096] @OSArch: X64
2: D [2023-06-13 17:26:03.097] @OSVersion: WIN_10
2: D [2023-06-13 17:26:03.098] @OSBuild: 19045
2: D [2023-06-13 17:26:03.099] @OSServicePack: 
2: D [2023-06-13 17:26:03.100] @AutoItVersion: 3.3.14.5
2: D [2023-06-13 17:26:03.101] xbebenkMod Version: v1.2.4[#106]
2: D [2023-06-13 17:26:03.102] Emulator: BlueStacks5
2: D [2023-06-13 17:26:03.103] Emulator Version: 5.12.0.1085
2: D [2023-06-13 17:26:03.104] Android Version: Pie
2: D [2023-06-13 17:26:03.105] Primary Display: 2560 x 1440 - 32bit
2: D [2023-06-13 17:26:03.079] Restore bot window to 2007, 19, caller: GUIControl_WM_SHELLHOOK
2: D [2023-06-13 17:26:54.660] Restore bot window to 2007, 19, caller: GUIControl_WM_NCACTIVATE
2: D [2023-06-13 17:26:56.357] Restore bot window to 2007, 19, caller: GUIControl_WM_NCACTIVATE
2: D [2023-06-13 17:27:17.411] Restore bot window to 2007, 19, caller: GUIControl_WM_NCACTIVATE
2: L [2023-06-13 17:27:17.432] Run Function : zoomOut()
2: L [2023-06-13 17:27:17.434] $g_aiBSpos X,Y = 1103,37; $g_aiBSrpos X,Y = 1,33
2: D [2023-06-13 17:27:17.435] ZoomOutBlueStacks5()
2: D [2023-06-13 17:27:17.435] DefaultZoomOut()
2: D [2023-06-13 17:27:17.436] aVillageCenteringCoord : [777,235]
2: D [2023-06-13 17:27:17.767] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2023-06-13 17:27:17.835] findImage imgloc search returned no results in 16,318|216,318|216,518|16,518 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneDS-116-418_0_92.xml' !
2: D [2023-06-13 17:27:17.836] GetVillageSize check for image stone10-165-439_0_93.xml
2: D [2023-06-13 17:27:17.883] findImage imgloc search returned no results in 65,339|265,339|265,539|65,539 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stone10-165-439_0_93.xml' !
2: D [2023-06-13 17:27:17.884] GetVillageSize check for image stone9C-143-500_0_93.xml
2: D [2023-06-13 17:27:17.922] findImage imgloc search returned no results in 43,400|243,400|243,600|43,600 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stone9C-143-500_0_93.xml' !
2: D [2023-06-13 17:27:17.923] GetVillageSize check for image stoneCC-123-498_0_93.xml
2: D [2023-06-13 17:27:17.969] findImage imgloc search returned no results in 23,398|223,398|223,598|23,598 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneCC-123-498_0_93.xml' !
2: D [2023-06-13 17:27:17.969] GetVillageSize check for image stoneCF-181-469_0_93.xml
2: D [2023-06-13 17:27:18.010] findImage imgloc search returned no results in 81,369|281,369|281,569|81,569 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneCF-181-469_0_93.xml' !
2: D [2023-06-13 17:27:18.012] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2023-06-13 17:27:18.049] findImage imgloc search returned no results in 16,318|216,318|216,518|16,518 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneDS-116-418_0_92.xml' !
2: D [2023-06-13 17:27:18.050] GetVillageSize check for image stoneEP-103-478_0_93.xml
2: D [2023-06-13 17:27:18.090] findImage imgloc search returned no results in 3,378|203,378|203,578|3,578 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneEP-103-478_0_93.xml' !
2: D [2023-06-13 17:27:18.091] GetVillageSize check for image stoneEW-142-453_0_93.xml
2: D [2023-06-13 17:27:18.135] findImage imgloc search returned no results in 42,353|242,353|242,553|42,553 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneEW-142-453_0_93.xml' !
2: D [2023-06-13 17:27:18.136] GetVillageSize check for image stoneHM-120-509_0_93.xml
2: D [2023-06-13 17:27:18.207] findImage imgloc search returned no results in 20,409|220,409|220,609|20,609 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneHM-120-509_0_93.xml' !
2: D [2023-06-13 17:27:18.208] GetVillageSize check for image stoneJL-118-440_0_93.xml
2: D [2023-06-13 17:27:18.247] findImage imgloc search returned no results in 18,340|218,340|218,540|18,540 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneJL-118-440_0_93.xml' !
2: D [2023-06-13 17:27:18.248] GetVillageSize check for image stoneJS-114-440_0_95.xml
2: D [2023-06-13 17:27:18.274] findImage imgloc search returned no results in 14,340|214,340|214,540|14,540 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneJS-114-440_0_95.xml' !
2: D [2023-06-13 17:27:18.333] GetVillageSize check for image stoneJS-83-472_0_93.xml
2: D [2023-06-13 17:27:18.378] findImage imgloc search returned no results in -17,372|183,372|183,572|-17,572 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneJS-83-472_0_93.xml' !
2: D [2023-06-13 17:27:18.379] GetVillageSize check for image stoneMS-163-417_0_93.xml
2: D [2023-06-13 17:27:18.429] findImage imgloc search returned no results in 63,317|263,317|263,517|63,517 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneMS-163-417_0_93.xml' !
2: D [2023-06-13 17:27:18.430] GetVillageSize check for image stonePC-86-465_0_93.xml
2: D [2023-06-13 17:27:18.463] findImage imgloc search returned no results in -14,365|186,365|186,565|-14,565 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePC-86-465_0_93.xml' !
2: D [2023-06-13 17:27:18.464] GetVillageSize check for image stonePG-148-435_0_93.xml
2: D [2023-06-13 17:27:18.502] findImage imgloc search returned no results in 48,335|248,335|248,535|48,535 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePG-148-435_0_93.xml' !
2: D [2023-06-13 17:27:18.503] GetVillageSize check for image stonePR-126-458_0_93.xml
2: D [2023-06-13 17:27:18.527] findImage imgloc search returned no results in 26,358|226,358|226,558|26,558 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePR-126-458_0_93.xml' !
2: D [2023-06-13 17:27:18.528] GetVillageSize check for image stonePS-125-409_0_93.xml
2: D [2023-06-13 17:27:18.586] findImage imgloc search returned no results in 25,309|225,309|225,509|25,509 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePS-125-409_0_93.xml' !
2: D [2023-06-13 17:27:18.587] GetVillageSize check for image stoneRY-138-480_0_93.xml
2: D [2023-06-13 17:27:18.640] findImage imgloc search returned no results in 38,380|238,380|238,580|38,580 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneRY-138-480_0_93.xml' !
2: D [2023-06-13 17:27:18.641] GetVillageSize check for image stoneSD-129-437_0_93.xml
2: D [2023-06-13 17:27:18.672] findImage imgloc search returned no results in 29,337|229,337|229,537|29,537 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSD-129-437_0_93.xml' !
2: D [2023-06-13 17:27:18.673] GetVillageSize check for image stoneSH-149-474_0_95.xml
2: D [2023-06-13 17:27:18.705] findImage imgloc search returned no results in 49,374|249,374|249,574|49,574 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSH-149-474_0_95.xml' !
2: D [2023-06-13 17:27:18.706] GetVillageSize check for image stoneSM-161-456_0_93.xml
2: D [2023-06-13 17:27:18.731] findImage imgloc search returned no results in 61,356|261,356|261,556|61,556 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSM-161-456_0_93.xml' !
2: D [2023-06-13 17:27:18.732] GetVillageSize check for image stoneSP-275-509_0_93.xml
2: D [2023-06-13 17:27:18.790] findImage imgloc search returned no results in 175,409|375,409|375,609|175,609 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSP-275-509_0_93.xml' !
2: D [2023-06-13 17:27:18.792] GetVillageSize check for image stoneTM-76-418_0_93.xml
2: D [2023-06-13 17:27:18.919] findImage imgloc search returned no results in -24,318|176,318|176,518|-24,518 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneTM-76-418_0_93.xml' !
2: D [2023-06-13 17:27:18.976] GetVillageSize check for image stoneW1-161-449_0_93.xml
2: D [2023-06-13 17:27:19.026] findImage imgloc search returned no results in 61,349|261,349|261,549|61,549 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneW1-161-449_0_93.xml' !
2: D [2023-06-13 17:27:19.027] GetVillageSize check for image stoneW2-91-466_0_93.xml
2: D [2023-06-13 17:27:19.108] findImage imgloc search returned no results in -9,366|191,366|191,566|-9,566 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneW2-91-466_0_93.xml' !
2: D [2023-06-13 17:27:19.110] stone: 0|0|0|0|0|
2: D [2023-06-13 17:27:19.111] GetVillageSize cannot find stone
2: D [2023-06-13 17:27:19.674] _checkMainScreenImage, Expected: 7ABDE0, Tolerance: 20 at X,Y: 279,9 Found: 020623
2: D [2023-06-13 17:27:19.697] aVillageCenteringCoord : [777,235]
2: D [2023-06-13 17:27:19.705] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2023-06-13 17:27:19.740] findImage imgloc search returned no results in 16,318|216,318|216,518|16,518 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneDS-116-418_0_92.xml' !
2: D [2023-06-13 17:27:19.742] GetVillageSize check for image stone10-165-439_0_93.xml
2: D [2023-06-13 17:27:19.788] findImage imgloc search returned no results in 65,339|265,339|265,539|65,539 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stone10-165-439_0_93.xml' !
2: D [2023-06-13 17:27:19.789] GetVillageSize check for image stone9C-143-500_0_93.xml
2: D [2023-06-13 17:27:19.827] findImage imgloc search returned no results in 43,400|243,400|243,600|43,600 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stone9C-143-500_0_93.xml' !
2: D [2023-06-13 17:27:19.828] GetVillageSize check for image stoneCC-123-498_0_93.xml
2: D [2023-06-13 17:27:19.869] findImage imgloc search returned no results in 23,398|223,398|223,598|23,598 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneCC-123-498_0_93.xml' !
2: D [2023-06-13 17:27:19.870] GetVillageSize check for image stoneCF-181-469_0_93.xml
2: D [2023-06-13 17:27:19.911] findImage imgloc search returned no results in 81,369|281,369|281,569|81,569 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneCF-181-469_0_93.xml' !
2: D [2023-06-13 17:27:19.912] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2023-06-13 17:27:19.948] findImage imgloc search returned no results in 16,318|216,318|216,518|16,518 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneDS-116-418_0_92.xml' !
2: D [2023-06-13 17:27:19.949] GetVillageSize check for image stoneEP-103-478_0_93.xml
2: D [2023-06-13 17:27:19.987] findImage imgloc search returned no results in 3,378|203,378|203,578|3,578 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneEP-103-478_0_93.xml' !
2: D [2023-06-13 17:27:19.989] GetVillageSize check for image stoneEW-142-453_0_93.xml
2: D [2023-06-13 17:27:20.034] findImage imgloc search returned no results in 42,353|242,353|242,553|42,553 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneEW-142-453_0_93.xml' !
2: D [2023-06-13 17:27:20.035] GetVillageSize check for image stoneHM-120-509_0_93.xml
2: D [2023-06-13 17:27:20.223] findImage imgloc search returned no results in 20,409|220,409|220,609|20,609 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneHM-120-509_0_93.xml' !
2: D [2023-06-13 17:27:20.266] GetVillageSize check for image stoneJL-118-440_0_93.xml
2: D [2023-06-13 17:27:20.304] findImage imgloc search returned no results in 18,340|218,340|218,540|18,540 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneJL-118-440_0_93.xml' !
2: D [2023-06-13 17:27:20.305] GetVillageSize check for image stoneJS-114-440_0_95.xml
2: D [2023-06-13 17:27:20.332] findImage imgloc search returned no results in 14,340|214,340|214,540|14,540 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneJS-114-440_0_95.xml' !
2: D [2023-06-13 17:27:20.333] GetVillageSize check for image stoneJS-83-472_0_93.xml
2: D [2023-06-13 17:27:20.376] findImage imgloc search returned no results in -17,372|183,372|183,572|-17,572 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneJS-83-472_0_93.xml' !
2: D [2023-06-13 17:27:20.378] GetVillageSize check for image stoneMS-163-417_0_93.xml
2: D [2023-06-13 17:27:20.429] findImage imgloc search returned no results in 63,317|263,317|263,517|63,517 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneMS-163-417_0_93.xml' !
2: D [2023-06-13 17:27:20.430] GetVillageSize check for image stonePC-86-465_0_93.xml
2: D [2023-06-13 17:27:20.474] findImage imgloc search returned no results in -14,365|186,365|186,565|-14,565 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePC-86-465_0_93.xml' !
2: D [2023-06-13 17:27:20.475] GetVillageSize check for image stonePG-148-435_0_93.xml
2: D [2023-06-13 17:27:20.512] findImage imgloc search returned no results in 48,335|248,335|248,535|48,535 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePG-148-435_0_93.xml' !
2: D [2023-06-13 17:27:20.513] GetVillageSize check for image stonePR-126-458_0_93.xml
2: D [2023-06-13 17:27:20.536] findImage imgloc search returned no results in 26,358|226,358|226,558|26,558 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePR-126-458_0_93.xml' !
2: D [2023-06-13 17:27:20.538] GetVillageSize check for image stonePS-125-409_0_93.xml
2: D [2023-06-13 17:27:20.704] findImage imgloc search returned no results in 25,309|225,309|225,509|25,509 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stonePS-125-409_0_93.xml' !
2: D [2023-06-13 17:27:20.705] GetVillageSize check for image stoneRY-138-480_0_93.xml
2: D [2023-06-13 17:27:20.749] findImage imgloc search returned no results in 38,380|238,380|238,580|38,580 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneRY-138-480_0_93.xml' !
2: D [2023-06-13 17:27:20.750] GetVillageSize check for image stoneSD-129-437_0_93.xml
2: D [2023-06-13 17:27:20.780] findImage imgloc search returned no results in 29,337|229,337|229,537|29,537 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSD-129-437_0_93.xml' !
2: D [2023-06-13 17:27:20.826] GetVillageSize check for image stoneSH-149-474_0_95.xml
2: D [2023-06-13 17:27:20.857] findImage imgloc search returned no results in 49,374|249,374|249,574|49,574 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSH-149-474_0_95.xml' !
2: D [2023-06-13 17:27:20.858] GetVillageSize check for image stoneSM-161-456_0_93.xml
2: D [2023-06-13 17:27:20.884] findImage imgloc search returned no results in 61,356|261,356|261,556|61,556 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSM-161-456_0_93.xml' !
2: D [2023-06-13 17:27:20.885] GetVillageSize check for image stoneSP-275-509_0_93.xml
2: D [2023-06-13 17:27:20.943] findImage imgloc search returned no results in 175,409|375,409|375,609|175,609 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneSP-275-509_0_93.xml' !
2: D [2023-06-13 17:27:20.944] GetVillageSize check for image stoneTM-76-418_0_93.xml
2: D [2023-06-13 17:27:20.962] findImage imgloc search returned no results in -24,318|176,318|176,518|-24,518 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneTM-76-418_0_93.xml' !
2: D [2023-06-13 17:27:20.963] GetVillageSize check for image stoneW1-161-449_0_93.xml
2: D [2023-06-13 17:27:21.011] findImage imgloc search returned no results in 61,349|261,349|261,549|61,549 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneW1-161-449_0_93.xml' !
2: D [2023-06-13 17:27:21.012] GetVillageSize check for image stoneW2-91-466_0_93.xml
2: D [2023-06-13 17:27:21.208] findImage imgloc search returned no results in -9,366|191,366|191,566|-9,566 for 'M:\Program\MBR_xbebenkMod-dev_1.2.4\MBR_xbebenkMod-dev_1.2.4\imgxml\village\NormalVillage\stone\stoneW2-91-466_0_93.xml' !
2: D [2023-06-13 17:27:21.209] stone: 0|0|0|0|0|
2: D [2023-06-13 17:27:21.210] GetVillageSize cannot find stone
2: D [2023-06-13 17:27:22.213] Zooming Out (DefaultZoomOut)

**Comment by KDB19** [comment]
I've done it all
But it doesn't work

**Comment by xbebenk** [comment]
use default scenery?
check on android tab:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/0b443e02-ce41-4cc0-96a4-f5748c6acd34)

also check your adb file size
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/20eacaf3-e2fa-423a-9d55-f912fc1a37b9)

**Comment by KDB19** [comment]
I need a little clarification. When I run function ZoomOut(), does the bot run? or be closed

**Comment by KDB19** [comment]
Finally, it worked, thank you

**Comment by xbebenk** [comment]
what make it work?

**Comment by KDB19** [comment]
Are these settings correct?

**Comment by KDB19** [comment]
This thing I can't find
Can you tell me its path?

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/4249c1a0-4b3f-4d2c-9db6-c0803cb321e9)
you need a loop?

**Comment by KDB19** [comment]
I can't find it

**Comment by KDB19** [comment]
![explorer_stEuSVmj2P](https://github.com/xbebenk/MBR_xbebenkMod/assets/136461177/e651dad0-14ec-45d6-89c1-cbdee1b1c879)

**Comment by KDB19** [comment]
I bothered you but can you give me an easy solution

**Comment by xbebenk** [comment]
there is no solution if the problem is not known

**Comment by KDB19** [comment]
My friend I have explained to you
 this which gets look at the pictures below
![AutoIt3_4cp4H1DNsz](https://github.com/xbebenk/MBR_xbebenkMod/assets/136461177/ad9aed72-f0b3-4a22-acb5-37fcf9f6384e)

  He keeps giving me this error      Try secondary village measuring...

**Comment by xbebenk** [comment]
click photo button
send the picture

**Comment by KDB19** [comment]
![2023-06-15_13 22 37](https://github.com/xbebenk/MBR_xbebenkMod/assets/136461177/afb97e77-a8c8-4c28-978e-96fa626029ab)

**Comment by xbebenk** [comment]
please use normal scenery (default one) or jungle (TH14) or magic (TH15)

**Comment by KDB19** [comment]
Okay, and finally, thanks

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/eabc4841-ff82-46ed-8b68-1f2f6cb5fe3f)

You waste 2 days because not read

**Comment by KDB19** [comment]
hahaha 
I swear to you, I didn't know what it was because of my language, I didn't understand its meaning until I sent you a picture and said use normal scenery And I remembered
