### ISSUE TITLE
Nox v7.0.5.8 shared folder issue.

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#121]
Newest DEV version doesn't seem to work with NOX anymore.  When I start the bot I get a new message about "shared folder c:\users\myusername\pictures\Nox Photo" followed by:
A restart of your computer might be required
for the applied changes to take effect
please wait while Nox and Coc start 
Nox (nox) running in window mode

(yes I rebooted)
Just sits there nothing happens now.   Was working last week, but was getting messages about shield and something about monkeys and bananas?

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/a889fb0a-10b8-4a6f-9b5b-54a889fc4b90)

**Comment by MassXXL** [comment]
That is Bluestacks shown (I can tell by the (PIE_64) should nox work now or should I look at Bluestacks?  I had both working but for sure NOX I can tweak and debloat and seems to work better for me past few years.

**Comment by xbebenk** [comment]
it is bs and nox run

**Comment by MassXXL** [comment]
[2023-06-13_20.01.32.log](https://github.com/xbebenk/MBR_xbebenkMod/files/11740378/2023-06-13_20.01.32.log)

True didn't look there for NOX :)
attach log file.

**Comment by MassXXL** [comment]
reinstalled NOX - and getting a tad more into it, but now at stage with waiting on shared folder to mount.  I will spin up a new OS instance with fresh NOX, and fresh bot install, with default profile so on and go from there.   Then re-upload debug logs if needed.  thank you.

**Comment by xbebenk** [comment]
your log line 380-384:
`<none>
Bandwidth groups:  <none>
Shared folders:  <none>
Guest:
Configured memory balloon size:      0 MB`

My Log :
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/3be78252-206c-4ca7-938f-8afd8428f53c)

**Comment by MassXXL** [comment]
Installed fresh Win10 on a new laptop- no other apps but what is needed for bot.
See attached log.
Just noticed that NOX released a new version.  So I am going to try that out.

[2023-06-14_20.48.58.log](https://github.com/xbebenk/MBR_xbebenkMod/files/11751690/2023-06-14_20.48.58.log)

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/47e36971-4766-463a-994b-64f6429af6bf)

enable debug message
run function: ConfigureSharedFolderNox()

**Comment by MassXXL** [comment]
Did give blusestacks a go again.   Seems to be working a bit but also have that smartwait4train issue - it is not working.
![Screenshot-on smartwait4train](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/cf6a1c94-3c58-4bf9-97f5-39a9a08967cf)

**Comment by xbebenk** [comment]
so what this issue about?
nox shared folder solved?

if solved, please tell what you do
close this issue and make another

**Comment by MassXXL** [comment]
Not solved - just saying NOX is not working and I figured I try BS5.11 out and see what happens.  IT works, but once the smart train should kick in it gives that monkey needs more bananas to read shield error.   Which in the end, it will run for 3 hours and the break period kicks in (like to avoid that I close bot during no shield).

So the NOX thing I provided a log.  I tried newest version of NOX and same issues with shared folder.

**Comment by xbebenk** [comment]
maybe you need to set shared folder on nox manually
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/f090a027-0f4b-4aec-b7d1-667718afd857)

**Comment by MassXXL** [comment]
Well that seemed to have did the trick.  Did you change the location in BOT to the new location?  I never have changed it from c:\users\username\Nox_share to c:\users\username\pictures\Nox Photo until now.    Also for a very long time using your DEV bot it has been to me the default location (Nox_share).

**Comment by xbebenk** [comment]
yes, i did change default value to ramdisk

**Comment by MassXXL** [comment]
Thank you issue is closed.
