### ISSUE TITLE
battle machine not dropping 

### ISSUE THREAD

**Issue by nhumber** [xbebenk/MBR_xbebenkMod#123]
latest commits, battle machine not dropping not first bb battle, 2nd builder base battle not working at all, no troops drop at all

**Comment by xbebenk** [comment]
you better send log when opening issue

**Comment by nhumber** [comment]
i have no where to send logs to you, if you message me on discord i could send you the logs.. i reverted back to ver #106 for now. 
discord ID Duke#4840

**Comment by xbebenk** [comment]
sent

**Comment by Hoith95** [comment]
Hello.
please adjust the code back to 37, this error does not happen anymore.

$Troopx = $aSlotX[$k]
![Screenshot 2023-06-16 140941](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/d150f32d-9fed-444f-9b2d-a19b1838fd29)
$ColorPickBannerX = $aSlotX[$k] + 37 ; location to pick color from TroopSlot banner

**Comment by xbebenk** [comment]
issue still?

**Comment by nhumber** [comment]
initial issue was already fixed up, going to close this
