### ISSUE TITLE
ERROR Cannot verify ArmyTrain Button

### ISSUE THREAD

**Issue by Hoith95** [xbebenk/MBR_xbebenkMod#124]
Cannot find Army Window...
[1:45:08 PM] Cannot verify ArmyTrain Button
[1:45:08 PM] expected FFFFE2, got CBCBC3
Hello.
while running mybot sometimes i get this error:
it makes the bot unable to identify the army and takes a long time to restart the emulator.
I have tried to fix this but it is possible that this error is caused by adb graphics factors because when I turn off Background mode, this error does not occur at all.
Currently I have found a temporary solution to fix this error is to add the code:
File code: OpenArmyOverview.au3
If $i > 2 Then CloseCoC(True)
![Screenshot 2023-06-16 134644](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/faaead05-438d-48f6-bc0d-9089ef250b99)
after closeCOC, this error is gone and the bot works normally.
I understand this problem is not really optimized and fixed the above problem but hopefully it will help you and Team for reference.
![Screenshot 2023-06-16 134527](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/68ece5ff-5618-4d83-a274-03c81a2ec443)

**Comment by NothingJustBlank** [comment]
Try running with OpenGL and adbscreencap on. 
Does that still produce an error?

**Comment by Hoith95** [comment]
> Hãy thử chạy với OpenGL và bật adbscreencap. Điều đó vẫn tạo ra một lỗi?

Thanks I'll try and let you know in 30 minutes.

**Comment by Hoith95** [comment]
Yes, it still has the error.
![Screenshot 2023-06-16 142613](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/a0205fe8-fc9f-4918-8fb7-a36875348bbc)
![Screenshot 2023-06-16 142623](https://github.com/xbebenk/MBR_xbebenkMod/assets/26041591/0c9153e4-9cc8-43eb-a361-47888fe243ef)

**Comment by Hoith95** [comment]
Currently, the latest dev version I have downloaded and tested still has the above error, let you know, many thanks for the efforts from you and the team.
![Uploading Screenshot 2023-06-17 022550.png…]()

**Comment by xbebenk** [comment]
stop bot,
enable debug message,
run function: OpenArmyOverview()

**Comment by Hoith95** [comment]
I followed and here is a video of me when the bot encounters this error, this error does not appear often but it directly affects the military training process.
https://youtu.be/FyfXzHvp-6s

**Comment by xbebenk** [comment]
you are using win11
thats why....
idk why color in win11 is not same as win10

try this:
on screencoordinates.au3 find $aIsTrainPgChk1
replace the line defining it with this:
Global $aIsTrainPgChk1[4] = [525, 107, 0xD51115, 20] ; Main Screen, Train page open - bottom of x button

**Comment by xbebenk** [comment]
i hope you notice, i edit the coord to 825,107

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/345fb1ae-a32d-4532-a2fc-7806bff3274b)
with this change bot will check color on this coord

**Comment by Hoith95** [comment]
yes I will follow and let you know right away.  once again thank you.

**Comment by Hoith95** [comment]
yes the error has been fixed after editing the code.
Thank you.
