### ISSUE TITLE
Smart Train without shield not working.

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#125]
Close While training without shield seems to be broken.    Looks like the personal break was removed on newest version, but I still would like this feature to work.  Attached log file and screen shot"

[2023-06-16_19.33.48.log](https://github.com/xbebenk/MBR_xbebenkMod/files/11777275/2023-06-16_19.33.48.log)

![Capture](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/7e74212e-c692-4fd4-849b-831f97130fea)

**Comment by xbebenk** [comment]
i never use this feature
can you capture your train option setting?

**Comment by xbebenk** [comment]
here is what i got
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/32110c51-a29f-4354-8e8f-3bfbc5726fcf)

**Comment by MassXXL** [comment]
**Main Window OK**
sorry, Monkey needs more bananas to read shield type
Result : 0

**Comment by xbebenk** [comment]
try:
_CheckPixel($aNoShield, $g_bCapturePixel)
_CheckPixel($aHaveShield, $g_bCapturePixel)
_CheckPixel($aHavePerGuard, $g_bCapturePixel)

**Comment by MassXXL** [comment]
![CheckPixel](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/08d3bd78-2fdb-4581-a046-53d8e07c3ac0)
all False.  Tested on Win11 and 10.  Only thing in common is Nvidia GPUs with newest drivers.

**Comment by xbebenk** [comment]
in fact what is your shield status?

**Comment by xbebenk** [comment]
Win10, Nox :
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/b8e90eeb-c157-4add-9225-200107e8409d)

Win10, BS5:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/c18177ba-51cc-4e28-8eed-ab0d63ada6ff)

**Comment by MassXXL** [comment]
No shield was active at the time I ran those commands.  Close while training - without shield.  

![Capture](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/c8407340-32d0-4d0c-8efd-3345acd24e52)

**Comment by xbebenk** [comment]
Run Function : _GetPixelColor(448, 20, True)

**Comment by MassXXL** [comment]
![Uploading Capture2.PNG…]()

**Comment by MassXXL** [comment]
Attached
![Capture2](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/f9218a2e-4d31-4776-a07f-c072f30f9186)

**Comment by xbebenk** [comment]
enable debug message, and please run this on:
Account that have No Shield:
_ColorCheck(_GetPixelColor(448, 20, True),"43484B", 15, Default, "HaveNoShield")

Account that have shield:
_ColorCheck(_GetPixelColor(455, 19, True),"F0F8FB", 15, Default, "HaveShield")

Account that have Guard:
_ColorCheck(_GetPixelColor(455, 19, True),"10100D", 15, Default, "HaveGuard")

**Comment by MassXXL** [comment]
NO Shield:
Run Function : _ColorCheck(_GetPixelColor(448, 20, True),"43484B", 15, Default, "HaveNoShield")
[HaveNoShield:False, Exp=303333, Got=43484B, Var=15, ixVar=21
Result : False

shield:
Run Function : _ColorCheck(_GetPixelColor(455, 19, True),"F0F8FB", 15, Default, "HaveShield")
Result : True


Guard:
Run Function : _ColorCheck(_GetPixelColor(455, 19, True),"10100D", 15, Default, "HaveGuard")
HaveGuard:False, Exp=5C38A2, Got=10100D, Var=15, ixVar=40
Result : False

**Comment by xbebenk** [comment]
please check last commit

**Comment by MassXXL** [comment]
Different resuilts, but still not working.

[2:46:19 PM] Run Function : _ColorCheck(_GetPixelColor(448, 20, True),"43484B", 15, Default, "HaveNoShield")
[2:46:19 PM] HaveNoShield:False, Exp=43484B, Got=303333, Var=15, ixVar=21
[2:46:19 PM] Result : False

![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/a78b4b0c-234b-4bd9-82c0-36c532aa9a59)

**Comment by xbebenk** [comment]
ignore that monkey2 message

**Comment by MassXXL** [comment]
Thank you again!  Closing issue.
