### ISSUE TITLE
Clan Games builder base.

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#127]
While doing a clan game event, the bot does "check challenges progress #1-XX" but it seems now when the check kicks in that pop-up it is looking for is well over and gone before the bot can even check the challenge.   Maybe you can change it so it can say check every 5 minutes on home base for status.  

I can provide the logs, but this is more about timing and how the challenge progresses window is very quick now.

![Screenshot 2023-06-26 180029](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/22ebcfa8-800a-4274-97b9-1375acd7177a)

**Comment by MassXXL** [comment]
![Screenshot 2023-06-26 180256](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/3d32892e-e537-404e-8ede-f3494efa7c1b)

**Comment by MassXXL** [comment]
Maybe this screen shot will show a little better of what I mean.  Challenge Progress pops quick and is gone before the Bot recovers from attack.

![Screenshot 2023-06-26 181407](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/35341faa-1eef-440b-ae28-6753c778ff28)

**Comment by NothingJustBlank** [comment]
set emulator to 20fps

**Comment by MassXXL** [comment]
Doesn't help.   Still missing the progress.
