### ISSUE TITLE
Builder Base - stuck on waiting for main screen.

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#128]
Using the newest Dev.   I have the bot running to do attacks in BB as well as home village, but to only attack if stars are available for BuilderBase.   Once it finishes all attacks it gets stuck in BB.   See screen shot.    

![Screenshot 2023-07-08 110004](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/2baa12af-ef50-47bb-b124-ceef214bd02e)

I am using ADB screencap

**Comment by xbebenk** [comment]
not enough info, please send log 
not stuck on mine:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/097a9969-5901-4f8b-9d4b-333d8713a35d)

**Comment by MassXXL** [comment]
See attached. At the end I just stopped the bot where it is looping on random click.

[2023-07-08_11.58.02.log](https://github.com/xbebenk/MBR_xbebenkMod/files/11991292/2023-07-08_11.58.02.log)

**Comment by MassXXL** [comment]
Used newest DEV and issue is resolved.  Thank you as always!!!
