### ISSUE TITLE
Clan Games home base events.

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#131]
Noticed that during clan games events (on-going now) that the BOT does pick a home base event just fine, but once it is completed, it never moves onto the next.  It use to do this just fine (back when this was a mod for mybot).   Builderbase events seems to be working now after I tweak the FPS to 10. 

But not working with Home base event games, any suggestions?  I do have the MISC check clan games early enabled.  But that works when first starting a bot.   Picks a event, compeltes it and I have to manually assign a new one. 

Been using this mod for a very long time as well...  So my choices in the bot have been the same.
Not sure if this is needs a log file or I am just missing something.

BB only events work great.  Had a bot run on BB and finished out the 4k in no time.

**Comment by NothingJustBlank** [comment]
Most of our team only runs BB only events. Please post more logs for Main village events.

**Comment by MassXXL** [comment]
Attached log.  one event for freeze at the end of the log.  I started bot over - it picked use freeze spell (which I have as a choice), attacked, and once it was finished it just skips all checks for Clan Games events.   Unlike BuilderBase.


[2023-07-25_18.23.46.log](https://github.com/xbebenk/MBR_xbebenkMod/files/12166260/2023-07-25_18.23.46.log)

**Comment by MassXXL** [comment]
More logs if it can help.  Thank you.  

[2023-07-26_20.01.46.log](https://github.com/xbebenk/MBR_xbebenkMod/files/12178338/2023-07-26_20.01.46.log)

[ClanGames.log](https://github.com/xbebenk/MBR_xbebenkMod/files/12178339/ClanGames.log)

**Comment by BabyDragonn** [comment]
Hi, bot also choosing one of the BB missions even all BB missions are all unchecked. I cant remember exact name of mission but its a new one and its about destroying some amount of buildings in BB wars. I dont have any logs now but i'll post it when the next CG begins. Thanks in advance.

**Comment by MassXXL** [comment]
Seems after every attack it says in log [1] 1st attack loop success.  Which flushes the log and seems to start anew.  
Next attack same thing.  Always skipping to check for clan event status.

Let me know if you need any more logs.   Would be nice to resolve this.

**Comment by BabyDragonn** [comment]
> Hi, bot also choosing one of the BB missions even all BB missions are all unchecked. I cant remember exact name of mission but its a new one and its about destroying some amount of buildings in BB wars. I dont have any logs now but i'll post it when the next CG begins. Thanks in advance.

This is the one:

![Task](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/b3dfc0d8-d3e1-4e56-b3c3-2ded112c5ad6)

**Comment by MassXXL** [comment]
I think it is also Building Breakdown.   It skips it as a builder base event, and if I select it to do it as a BB event, the BOT will purge it.

![Building Break Down](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/017e692b-9443-4052-ae46-26c0aed4cfe1)

**Comment by MassXXL** [comment]
Yea - that is also same icon for the multiplayer event called building breakdown. 

![Building Break Down](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/5798359c-a5f1-4ac9-b33f-89439f2a55f2)

**Comment by MassXXL** [comment]
going to close this since everything changed now with new forced update.
