### ISSUE TITLE
waitMainScreen 

### ISSUE THREAD

**Issue by KDB19** [xbebenk/MBR_xbebenkMod#134]
Hello, I don't know, the problem suddenly appeared, I tried everything that didn't work, is there anything I can do 
![AutoIt3_D2bYq1SvHx](https://github.com/xbebenk/MBR_xbebenkMod/assets/136461177/7b18383d-b104-4eaa-bac1-d20dcc41c530)

**Comment by MassXXL** [comment]
It's from the new version of Clash 15.352.14 downgrade back to 15.352.8 for now.   Issue still needs to be fixed.  Not sure what the update did or does, but does stop the bot from working.   Had same issue and just restored my NOX backup using 15.352.8.
