### ISSUE TITLE
Update Mod to work with Clash version 15-352-22? 

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#138]
Would it be possible to get this amazing mod updated to 15-352-22 like the main bot just did?
Your mod works better in clan games, and in builder base by attacks, but drop empty siege is a nice option...

**Comment by NothingJustBlank** [comment]
no, update until there is a forced game update from SC. we will not waste our time until SC decides to not change font sizes, GUI sizes, etc

**Comment by MassXXL** [comment]
Ok thanks for the update. Make sense to me.

**Comment by MassXXL** [comment]
closed

**Comment by MassXXL** [comment]
well - guess that all changed today...
