### ISSUE TITLE
The zoomout() function no longer works

### ISSUE THREAD

**Issue by ludodoucet** [xbebenk/MBR_xbebenkMod#140]
The zoomout() function no longer works, it cannot find the stone.

**Comment by mathwo** [comment]
Yeah... need some rework to make the mod work for latest game update

**Comment by ludodoucet** [comment]
Of course, there is a lot of work, especially on the size of certain interfaces which has changed, I only wanted to make my contribution... but we will leave it to those who are used to this hard work.. .
