### ISSUE TITLE
incorrect OCR for army size

### ISSUE THREAD

**Issue by TwelveExit** [xbebenk/MBR_xbebenkMod#141]
hello,

I have full army size but bot cannot detect it.

For example when I have full army trained and ready for attack.
What I see: "Total Army Camp Capacity: **275/275** "
Bot log says: "Total Army Camp Capacity: **27/275** "

Bot version: latest build dev 1.2.5 Commits on Oct 28, 2023
Emulator: Nox 7.0.5.9
OS: Win10

I have tried for multiple accounts and bot cannot detect army size on half of the accounts.

Bot cannot detect trained army size if army is 250, 260, 270, 275, 285, 295, 315
Bot has no issues in detecting army size if it is 290, 300, 310, 320

I have your discord and can provide log and images if needed.

cheers,

**Comment by BabyDragonn** [comment]
It's an old problem, i reported this before but i guess since it's related to a very limited time of the account progress xbebenk couldnt give priority to that bug. And probably there are tons of things to do in his list to run the bot as in good old days after all those silly game updates.

**Comment by TwelveExit** [comment]
This was only related to october update and it used to work before. Thanks to the great work of xbebenk, it is now fixed 😀
