### ISSUE TITLE
emulator?

### ISSUE THREAD

**Issue by eginli24** [xbebenk/MBR_xbebenkMod#147]
Hello, which emulator and which version should be preferred to use the program?

**Comment by MassXXL** [comment]
I see xbebenk making updates to code after the TH16 update, but not even sure what emulator is being used...
NOX is for not working...
MEMU 9.x does work for me, but I get flooded with MEmu error launching ADB shell for minitouch.

**Comment by Dasuky** [comment]
BlueStacks5 version: 5.13.210.1007 
(instance Pie64)

**Comment by eginli24** [comment]
> BlueStacks5 version: 5.13.210.1007 (instance Pie64)

ty
