### ISSUE TITLE
Siege Donations

### ISSUE THREAD

**Issue by BabyDragonn** [xbebenk/MBR_xbebenkMod#148]
Hi, thank you for the great work. Donate sieges dont work for me.

**Comment by BabyDragonn** [comment]
Hello, i see some updates about this but its still not donating log launchers if you're not aware. Thanks again.

**Comment by xbebenk** [comment]
it donate on mine

**Comment by BabyDragonn** [comment]
This is the result for me;
![siege_d](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/4094ad18-21f0-4078-9b27-b23d41816aaf)
This account has 6 log launchers ready to donate but mod says "No siege machines available, skip siege donation"

**Comment by xbebenk** [comment]
checkArmyCamp(True)

**Comment by BabyDragonn** [comment]
They're all good, farming with same setting for a long time, this happened after th16 update.
![siege_d1](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/7874ba7b-415d-43e4-a663-c4dd70ec0f40)

**Comment by xbebenk** [comment]
stop bot
go to debug tab
enter checkArmyCamp(True)
then hit Run Function button

**Comment by BabyDragonn** [comment]
[2023-12-22_01.32.36.log](https://github.com/xbebenk/MBR_xbebenkMod/files/13746715/2023-12-22_01.32.36.log)
Still :(

**Comment by xbebenk** [comment]
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/fb98b5e2-99cf-4ad7-99db-15b4f6cb56dc)

bot should know wheter you have siege on your armycamp

**Comment by BabyDragonn** [comment]
![siege_d2](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/e57bb876-7969-4399-888a-e5cd085260c8)
Not showing siege info for me.

**Comment by nhumber** [comment]
seiges working good after 6531cd0

training time left detection still not working unless time remaining is under 10 minutes. (single digits)

**Comment by BabyDragonn** [comment]
Siege training is working good after that, its right. But not donating.

**Comment by nhumber** [comment]
> Siege training is working good after that, its right. But not donating.

donating fine here

**Comment by nhumber** [comment]
[6:24:57 AM] Checking Spell tab: 22/22
[6:24:57 AM] Cur = Max
[6:24:57 AM] Open Build Siege Machines Tab
[6:24:58 AM] - Wall Wrecker x3 Queued.
[6:25:03 AM] Time Idle: 00:02:18
[6:25:03 AM] Start Switch Account!
**[6:25:04 AM] Troops Time: 0 min**
[6:25:05 AM] Requesting Clan Castle reinforcements
[6:25:06 AM] Clan Castle Request has already been made
[6:25:07 AM] Army is ready, skip switching account
[6:25:10 AM] Click 236,6,1,0 #0000 | Away
[6:25:11 AM] ====== Waiting for full army ======


really slowing down the account switching since it cant figure out how much training time is left.
bot currently stays on account until 2 attacks are finished.

**Comment by NothingJustBlank** [comment]
> [6:24:57 AM] Checking Spell tab: 22/22 [6:24:57 AM] Cur = Max [6:24:57 AM] Open Build Siege Machines Tab [6:24:58 AM] - Wall Wrecker x3 Queued. [6:25:03 AM] Time Idle: 00:02:18 [6:25:03 AM] Start Switch Account! **[6:25:04 AM] Troops Time: 0 min** [6:25:05 AM] Requesting Clan Castle reinforcements [6:25:06 AM] Clan Castle Request has already been made [6:25:07 AM] Army is ready, skip switching account [6:25:10 AM] Click 236,6,1,0 #0000 | Away [6:25:11 AM] ====== Waiting for full army ======
> 
> really slowing down the account switching since it cant figure out how much training time is left. bot currently stays on account until 2 attacks are finished.

known issue, OCR for training time is not trained just yet

**Comment by BabyDragonn** [comment]
![siege_d3](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/20213a03-71c9-4e36-a72f-e823ea832a5e)

**Comment by BabyDragonn** [comment]
I find the reason why its not donating log launchers. I changed all my accounts to wall wreckers and donation worked. So there's still a problem with donating log launchers, bot doesnt recognize log launchers while donating.
