### ISSUE TITLE
TH16 update - bluestacks and NOX (patched to work) my small issues

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#149]
Thank you for all your work on the mod, home village raids work so far.  Builder Base attacks work (1st time) but get stuck on return home after battle is over.  This happens on both BS 5.14.10 and NOX (patched).

**Comment by MassXXL** [comment]
Home raids, siege machines do not train...

**Comment by MassXXL** [comment]
Here is a screen shot of the BB - waiting on main screen after the 1st attack. 

![BB-waiting-main-screen](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/4c49eb20-199c-4122-9a1c-c11d4ef0c87d)

**Comment by xbebenk** [comment]
next time, when it happen, do capture with photo button on bot

**Comment by MassXXL** [comment]
![2023-12-21_12 28 56](https://github.com/xbebenk/MBR_xbebenkMod/assets/136465245/5c823fe0-a8ba-4f7c-91c9-dae299637a25)

attached.

**Comment by MassXXL** [comment]
Seems all to be working! thank you!
