### ISSUE TITLE
2nd Super Troop Boost not Working

### ISSUE THREAD

**Issue by BabyDragonn** [xbebenk/MBR_xbebenkMod#157]
Hi. Mod is boosting first super troop without problem. But for example i boost another super troop for CWL and if first super troop's time run out while 2nd one is boosted mod cant boost first one again. It takes the account in sleep mod since it cant boost my main troop and make my army camps ready. Thanks.

**Comment by xbebenk** [comment]
known problem
don't know when have time to look at this

**Comment by BabyDragonn** [comment]
This is working great now, thanks.
