### ISSUE TITLE
disable builder hut upgrade during Rush TH?

### ISSUE THREAD

**Issue by TwelveExit** [xbebenk/MBR_xbebenkMod#159]
hey, is it possible to disable "Builder Hut" and "Spell Tower" upgrade when "Rush TH" is checked ? I see it as a waste of time and resource upgrading these when you could instead go to a higher town hall level.

**Comment by xbebenk** [comment]
on Auto Upgrade.au3
find this line : 
Local $aRushTHPriority[9][2] = [["Castle", 15], ["Pet", 15], ["Laboratory", 15], ["Storage", 14], ["Army", 13], ["Giga", 12], ["Town", 10], ["Hut", 10], ["Blacksmith", 15]]

change to:
Local $aRushTHPriority[8][2] = [["Castle", 15], ["Pet", 15], ["Laboratory", 15], ["Storage", 14], ["Army", 13], ["Giga", 12], ["Town", 10], ["Blacksmith", 15]]

**Comment by TwelveExit** [comment]
applied, thanks
