### ISSUE TITLE
Army size read error

### ISSUE THREAD

**Issue by xbebenk** [xbebenk/MBR_xbebenkMod#161]
@xbebenk There are still issues with the train army.  The commit you did last night fixed part of the issues but there are still issues.  I'm seeing issues in my armies when using GiWiz that giants seem to be training but not wizards.  To make matters worse, the army size for the Giants is more than what is setup to train and the bot isn't going back to remove the overage of Giants or training the wizards.  Here is one of my logs from the latest commit.  I'll check the other accounts soon where I'm using Super Barbarians.

https://pastes.io/spyzniqob6

_Originally posted by @benhayes36 in https://github.com/xbebenk/MBR_xbebenkMod/issues/160#issuecomment-1913682093_
           

2: L [2024-01-28 12:09:52.257] ====== TrainSystem =====
2: L [2024-01-28 12:09:53.341] **Army Window OK**
2: L [2024-01-28 12:09:53.342] **Army Window OK**
2: D [2024-01-28 12:10:15.648] AdbScreencap: 89/84/78 ms (all/10/1),0,0,l=155,t=170,w=80,h=16, 8C5A1527228FCCC55F72BBBA1EA86F3B9AC20032: w=860,h=676,f=1
2: L [2024-01-28 12:10:27.702] Army size read error, Troop numbers may not train correctly
2: D [2024-01-28 12:10:28.201] Can Request CC: False
2: L [2024-01-28 12:10:28.705] Total Army Camp Capacity: 0/240 (0%)

part of your log ^^
seem you have different problem
I need capture from photo button with army window open

**Comment by benhayes36** [comment]
I'll get this started tomorrow morning and send the pics over when I encounter the issue.

**Comment by benhayes36** [comment]
@xbebenk I'll explain the issue a bit more and will provide you the log from another account which is using the GiWiz.  The issue which the bot is showing is:

[9:12:02 AM] No Wizard Icon found!
[9:12:02 AM] No Wizard Icon found!
[9:12:02 AM] TrainIt troop position Wizard did not find icon
[9:12:03 AM] No Wizard Icon found!
[9:12:03 AM] TrainIt troop position Wizard did not find icon
[9:12:03 AM] No Wizard Icon found!
[9:12:03 AM] TrainIt troop position Wizard did not find icon
[9:12:04 AM] No Wizard Icon found!
[9:12:04 AM] TrainIt troop position Wizard did not find icon

On this particular account, it was missing the Wizards so I trained them manually.  The bot did other things (BB and other items).  The bot goes to train the 2nd army before an attack and is displaying the above error.

Here is the log from that account:

https://pastes.io/rusytd9j7e

Here is the image file that I took.

![2024-01-29_09 17 37](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/1698d369-9494-4274-89a7-cd29ec589ebb)

**Comment by benhayes36** [comment]
Here is another account with the issue (and photo of the army tab).  Log is attched (url).

https://pastes.io/z4i5ljpvqq

![2024-01-29_12 32 12](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/15513e43-1e3b-46f0-88e4-4c14361fcf07)

**Comment by xbebenk** [comment]
fixed wizard train on last commit
