### ISSUE TITLE
New TownHall upgrade prompt/window

### ISSUE THREAD

**Issue by benhayes36** [xbebenk/MBR_xbebenkMod#162]
@xbebenk There is a new Townhall upgrade window / prompt (an additional window opens if the game determines that your account is rushed and you try to start the Townhall upgrade).  I mistakenly clicked the Continue button before I took a screenshot of this.  On the next Townhall upgrade I do on one of my accounts, I will take a photo and provide it here.  Just wanted you to be aware of this because this window causes the bot to get stuck.

**Comment by benhayes36** [comment]
![2024-01-30_20 13 58](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/a593e58f-3cd2-4fa9-ad86-ddf71c59fa98)

This is the window.  The troop/spell/hero info will be different but the buttons below that should be consistent.

**Comment by xbebenk** [comment]
this should fixed

**Comment by xbebenk** [comment]
already added
