### ISSUE TITLE
Train & Read issues

### ISSUE THREAD

**Issue by benhayes36** [xbebenk/MBR_xbebenkMod#163]
@xbebenk After last commit to fix Wizard Train issues, I'm seeing issues where Giants were not training and reading Spells (plus more).  Below is the log link as well as photos taken from the bot.

https://pastes.io/tt954nv3h6

![2024-02-01_21 12 20](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/fa03ecc0-e61f-46c9-9c29-5e1f80d462f2)
![2024-02-01_21 13 02](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/13615559-842c-460a-a6a7-4634f7f76c96)

**Comment by xbebenk** [comment]
your log not reflecting photo you sent
what TH level there? 
if I were you, i will just gem to TH11 and train suba instead

**Comment by benhayes36** [comment]
> your log not reflecting photo you sent what TH level there? if I were you, i will just gem to TH11 and train suba instead

In regards to the picture, I stopped the bot and took the pictures from that account.  So not sure what else would be needed.  In regards to gemming to TH11, this is one option if it were only just 1 account.  I have many accounts from TH8 - TH10 which will need to farm until I get to stage where I could do the upgrade to TH11.  This issue that I'm seeing affects many of my accounts which are using GiWiz but from the logs it was having issues reading the Spell Capacity which stated 0/11 and my account had 22 zap spells trained - which I took pictures from two tabs.  There is some underlying issues in multiple areas.

**Comment by xbebenk** [comment]
I were have many accounts
all rushed to th11 with all barbs or all archs for attack
just need to train 1 barbs and 1 lightning on train setting
enable fill incorrect combo troops and spell on misc mod tab
should solve train issue

**Comment by BabyDragonn** [comment]
I'm also having some weird issues about reading train info, yes its less but still sometimes happens. And this makes skip to the next account without attacking. For example;
https://pastes.io/otvqvysijj

**Comment by BabyDragonn** [comment]
![11](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/8b5e0145-beb9-44f3-901b-84d1f6a3eb57)
![22](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/ae99e42b-dd01-485a-a52d-94560765e6b7)
![33](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/7e8449cc-b083-40ed-9586-4566f9a84573)
![44](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/adabd185-66b2-4601-93c3-bacf6aeac445)

This acc.3 didnt make an attack in this cycle but bot says "this account has attacked twice in a row, switching to another accunt". Account is not on hold status. And also u can see errors in first and second screenshots.

**Comment by BabyDragonn** [comment]
![55](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/7e27c70a-9a19-44ed-a016-baf04a0ebb33)
This is the attack log of these accounts. As you can see, no attack with acc.3.

**Comment by BabyDragonn** [comment]
Hi, i'll try to give any details u need. First, there's no difference between this acc.3 and others, for example in this instance all 8 accounts are very similar th16s, they are almost same in everything, their profiles are copied from same profile. Also acc.3 is just an example, this doesnt always happen for acc.3, in another cycle same thing happens on acc.1 and acc.3 attacks without problem.
This happens when bot cant open army window, this makes the bot trying to read army infos while army tab is not opened.
If you check the time 20:48:36, bot waits to see whats going on army tab and waits for 43 seconds until 20:49:19. But couldnt able to open army tab at that time. I tried to pause the bot and open army tab manualy at that waiting period when this happened in other account and bot reads army info and continue without problem. So it seems openning army tab is the main problem for this but no idea when bot cant open this tab, its just random.

**Comment by xbebenk** [comment]
when bot say "army size read error" bot expecting army overview window
what you see on emulator?

**Comment by BabyDragonn** [comment]
Just main screen, and no army tab. I can send screen next time i catch the error.

**Comment by BabyDragonn** [comment]
And it happened now in other account. Here is the ss.
![2024-02-09_15 28 01](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/1b4f63b6-59c3-4b56-b27b-30cebad72139)
![111](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/cfd8eb89-4bae-493f-9844-60f4379e3fdb)

**Comment by benhayes36** [comment]
@BabyDragonn In order for xbebenk to troubleshoot the issue, he needs to see the logs. Showing pictures and just info what the bot says isn't enough. Look at the logs to determine "exactly" what the issue is.

**Comment by BabyDragonn** [comment]
Hi @benhayes36 i already sent logs here;
> I'm also having some weird issues about reading train info, yes its less but still sometimes happens. And this makes skip to the next account without attacking. For example; https://pastes.io/otvqvysijj

I'm sending more screens and info to describe the problem with more details. Anyways, here's the logs of latest screenshots;
https://pastes.io/hmphm2kg4v

Problem starts at time: 15:25:21.675 After couldnt open army tab and read army info, bot passes to next account. And i stopped the bot manualy and pushed the same account back a few minutes after, then bot did 2 attacks without problem. As i said its just random, it sometimes cant open army tab and cant attack and sometimes works perfectly.

**Comment by xbebenk** [comment]
try latest commit, it verbosed log for opening army window

**Comment by BabyDragonn** [comment]
Thanks a lot, i'll use it and report you how will it work.

**Comment by BabyDragonn** [comment]
Hi, thanks again, i run the bot for the last 10 hours and previous problem didnt happen again. 💛
This can be closed for my side.

**Comment by xbebenk** [comment]
no recent issue
