### ISSUE TITLE
Not Donating Log Launchers

### ISSUE THREAD

**Issue by BabyDragonn** [xbebenk/MBR_xbebenkMod#166]
Hi, bot is not donating log launchers. There is no problem with blimp or wall wrecker, only the log launcher. Same thing was happened last time bot had donation problems and it was fixed with an update. It'd be great if u can check it please. Thanks.
PS: I did some tests now and it also not donating battle drills.

**Comment by xbebenk** [comment]
a log file with screenshot would be easier to catch the problem
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/cc47aeb7-4e87-4c2d-9c84-bf285a7dde45)

**Comment by BabyDragonn** [comment]
Hi, there is a line "2: D [2024-03-12 03:59:39.422] Bad call of CheckDonateTroop: Log Launcher", i dont know what is Bad call but seems its about it.
[2024-03-12_03.59.14.log](https://github.com/xbebenk/MBR_xbebenkMod/files/14565917/2024-03-12_03.59.14.log)
![2024-03-12_04 00 29](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/04460dc3-035f-4560-a034-a25894b990f0)
It doesnt care my siege request  if its log launcher but it fills a wall wrecker request perfectly.
![ll](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/3e74f8b0-c8c3-4dbc-9e7f-bcebf6027cd4)

**Comment by xbebenk** [comment]
bot failed read log launcher on request (if requested by image) check latest commit

**Comment by BabyDragonn** [comment]
> bot failed read log launcher on request (if requested by image) check latest commit

Hi, i actually request with both log launcher image and also keyword in our language.
And thank you very much, its now donating log launchers with the latest commit.
