### ISSUE TITLE
Possible missing image file and sieges not donating

### ISSUE THREAD

**Issue by benhayes36** [xbebenk/MBR_xbebenkMod#169]
xbebenk

I'm having an issue where sieges are not getting donated (in my case this is wall wreckers).  I have wall wreckers configured in the donation tab and got it set on several keywords.  But none of my accounts are donating (got 3 switch groups rotating 15 accounts).  I have just seen in the logs its complaining about a possible missing file.  But this issues has been going on for at least a good month or more.  When I saw this a couple weeks back, the bot saw the keyword (and the bot was set to donate) but the bot stated something along the lines that it was set to be excluded/ignored or something along those lines.  Here is my current log file of one of my bots running now:

https://pastes.io/cy7j92gd9g

**Comment by benhayes36** [comment]
Found it.  On line 2132, it says:

2: L [2024-03-18 20:23:37.226] Siege donation is not enabled, skip siege donation

BUT all my TH12+ accounts are set to train Wall Wreckers and donate Wall Wreckers.  But for some reason, the bot seems to think its not enabled.

**Comment by benhayes36** [comment]
yes, it's set.

![Bharat WW donation setting](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/29bcbe54-07df-49ca-9eca-bef713555378)

**Comment by benhayes36** [comment]
As said, all my TH12+ have wall Wreckers set tk donation. Whenever I look at the clan chat I can see all the requests waiting for sieges. But this has been going on for weeks (just getting around to reporting it now).

**Comment by xbebenk** [comment]
im not having problem with wallwrecker donation
maybe you should try clean profile to test, enable ww donation, save profile from profile tab
enable debug message
run donatecc(true) function
