### ISSUE TITLE
Purging too much CG events

### ISSUE THREAD

**Issue by BabyDragonn** [xbebenk/MBR_xbebenkMod#170]
Hello, im not sure if we can say its an issue but bot purging too much events. It almost never take an event to complete, just purging everything possible. For example there are 8 events thats whitelisted and can easily take it and finish but bot prefers to continue purge other 4 events. This was not working like that maybe 3-4 CG before this month. Bot was easily farm near 4k points in 1-1,5 days. But for the last 2 or 3 CG almost every accounts got 150-500 points after 3 days since bot purges too much than needed.
I hope i could describe the situation well, thanks in advance.

P.S.: Btw bot is still picking a builder base mission instead of Building Breakdown mission from main village coz they both have the same picture.

**Comment by xbebenk** [comment]
be sure you enable what challenge that you says it white listed.
enable clan games debug, post a log here. 

![HD-Player_YPkGepimzp](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/c24290e6-f0b3-4f37-9112-d3e2ed2d659c)

**Comment by BabyDragonn** [comment]
![1](https://github.com/xbebenk/MBR_xbebenkMod/assets/141275996/dd1d43b9-4f7d-461b-ae3f-a8a402239608)
Sure ill send logs in the afternoon but this is what happens. There were 6 missions enabled in my settings to pick from those 64 missions. But instead of getting a mission to get points bot^s priority is to purge. Ill send my settings and picture of what missions available at that time.
And yes im sure that account is not on halt mode.

**Comment by xbebenk** [comment]
then you need to enable debug image
show your enabled events on clan games settings
show emulator screenshot from photo button when bot searching events
