### ISSUE TITLE
Newest DEV version will not train spells correctly.  Endless loop on train.

### ISSUE THREAD

**Issue by MassXXL** [xbebenk/MBR_xbebenkMod#172]
I am using MEMU 9.0.5 with DirectX and after a good attack, the bot trains troops, but once on the spell tab it loops by adding the correct spells and then removing them. I am using newest version of MOD. 

[9:21:13 AM] IsNormalSpellTrain = True
[9:21:13 AM] Army Window OK
[9:21:14 AM] Checking spell queue: 22/22
[9:21:14 AM] $ArmyCamp[0] = 22 < $ArmyCamp[1] + $iTotalQueue = 32
[9:21:14 AM] A big guy blocks our camp
[9:21:14 AM] RemoveQueueSpell SpellIndex = 0, Quantity = 1
[9:21:14 AM] Army Window OK
[9:21:15 AM] Remove Big Guy on queue
[9:21:15 AM] Found x1 Heal
[9:21:15 AM] - Removing x1 queued Heal
[9:21:16 AM] Checking Spell tab: 20/22 remain space:-9
[9:21:16 AM] 20 > 11
[9:21:16 AM] IsNormalSpellTrain = True
[9:21:16 AM] RemoveTrainSpell, QueueOnly=True
[9:21:16 AM] Army Window OK
[9:21:17 AM] Checking spell queue: 20/22
[9:21:17 AM] $ArmyCamp[0] = 20 < $ArmyCamp[1] + $iTotalQueue = 30
[9:21:17 AM] A big guy blocks our camp
[9:21:17 AM] RemoveQueueSpell SpellIndex = 0, Quantity = 1
[9:21:17 AM] Army Window OK
[9:21:17 AM] Remove Big Guy on queue

**Comment by MassXXL** [comment]
Seems to be related to TH16.  I have a TH13 seems to be just fine can train new spells without looping.

**Comment by MassXXL** [comment]
Some of the log output from a TH16 base.  I do not have 11 Freeze spells set in attacks.  4 rage 1 heal and 1 freeze. 

2: L [2024-03-27 20:49:10.026] **Army Window OK**
2: D [2024-03-27 20:49:10.029]  imgloc searching for: BrewSpellsTab : C:\MBR\MyBot\imgxml\imglocbuttons\BrewSpellsTab_0_92.xml
2: D [2024-03-27 20:49:10.048] BrewSpellsTab Button Image Found in: 1|382,136
2: D [2024-03-27 20:49:10.320] FSpell | $aCoordArray: 631-218
2: D [2024-03-27 20:49:10.320] HSpell | $aCoordArray: 753-218
2: D [2024-03-27 20:49:10.321] RSpell | $aCoordArray: 691-217
2: D [2024-03-27 20:49:10.328] HSpell (724) x1
2: D [2024-03-27 20:49:10.334] RSpell (663) x4
2: D [2024-03-27 20:49:10.362] FSpell (602) x11
2: L [2024-03-27 20:49:10.362] Remove Big Guy on queue
2: L [2024-03-27 20:49:10.363] Found x1 Heal
2: L [2024-03-27 20:49:10.364]   - Removing x1 queued Heal
2: L [2024-03-27 20:49:11.574] Checking Spell tab: 20/22 remain space:-9
2: L [2024-03-27 20:49:11.575] 20 > 11
2: L [2024-03-27 20:49:11.576] IsNormalSpellTrain = True
2: L [2024-03-27 20:49:11.576] RemoveTrainSpell, QueueOnly=True
2: L [2024-03-27 20:49:11.682] **Army Window OK**
2: D [2024-03-27 20:49:11.687]  imgloc searching for: BrewSpellsTab : C:\MBR\MyBot\imgxml\imglocbuttons\BrewSpellsTab_0_92.xml
2: D [2024-03-27 20:49:11.706] BrewSpellsTab Button Image Found in: 1|382,136
2: L [2024-03-27 20:49:12.570] Checking spell queue: 20/22
2: D [2024-03-27 20:49:12.631] FSpell | $aCoordArray: 690-218
2: D [2024-03-27 20:49:12.631] RSpell | $aCoordArray: 752-217
2: D [2024-03-27 20:49:12.637] RSpell (724) x4
**2: D [2024-03-27 20:49:12.642] FSpell (663) x11**
2: L [2024-03-27 20:49:12.643] $ArmyCamp[0] = 20 < $ArmyCamp[1] + $iTotalQueue = 30
2: L [2024-03-27 20:49:12.643] A big guy blocks our camp
2: L [2024-03-27 20:49:12.645] RemoveQueueSpell SpellIndex = 0, Quantity = 1
2: L [2024-03-27 20:49:12.759] **Army Window OK**
2: D [2024-03-27 20:49:12.763]  imgloc searching for: BrewSpellsTab : C:\MBR\MyBot\imgxml\imglocbuttons\BrewSpellsTab_0_92.xml
2: D [2024-03-27 20:49:12.784] BrewSpellsTab Button Image Found in: 1|382,136
2: D [2024-03-27 20:49:13.038] FSpell | $aCoordArray: 690-218
2: D [2024-03-27 20:49:13.038] RSpell | $aCoordArray: 752-217
2: D [2024-03-27 20:49:13.044] RSpell (724) x4
2: D [2024-03-27 20:49:13.048] FSpell (663) x11
2: L [2024-03-27 20:49:13.049] Remove Big Guy on queue
2: L [2024-03-27 20:49:13.050] Found x4 Rage
2: L [2024-03-27 20:49:13.051]   - Removing x4 queued Rage
2: L [2024-03-27 20:49:14.776] Checking Spell tab: 12/22 remain space:-1
2: L [2024-03-27 20:49:14.776] 12 > 11
2: L [2024-03-27 20:49:14.777] IsNormalSpellTrain = True
2: L [2024-03-27 20:49:14.778] RemoveTrainSpell, QueueOnly=True
2: L [2024-03-27 20:49:14.905] **Army Window OK**
2: D [2024-03-27 20:49:14.909]  imgloc searching for: BrewSpellsTab : C:\MBR\MyBot\imgxml\imglocbuttons\BrewSpellsTab_0_92.xml
2: D [2024-03-27 20:49:14.927] BrewSpellsTab Button Image Found in: 1|382,136
2: L [2024-03-27 20:49:15.791] Checking spell queue: 12/22
2: D [2024-03-27 20:49:15.851] FSpell | $aCoordArray: 753-218
2: D [2024-03-27 20:49:15.857] FSpell (724) x11
2: L [2024-03-27 20:49:15.858] $ArmyCamp[0] = 12 < $ArmyCamp[1] + $iTotalQueue = 22
2: L [2024-03-27 20:49:15.859] A big guy blocks our camp
2: L [2024-03-27 20:49:15.860] RemoveQueueSpell SpellIndex = 0, Quantity = 1
2: L [2024-03-27 20:49:15.960] **Army Window OK**
2: D [2024-03-27 20:49:15.965]  imgloc searching for: BrewSpellsTab : C:\MBR\MyBot\imgxml\imglocbuttons\BrewSpellsTab_0_92.xml
2: D [2024-03-27 20:49:15.985] BrewSpellsTab Button Image Found in: 1|382,136
2: D [2024-03-27 20:49:16.238] FSpell | $aCoordArray: 753-218
2: D [2024-03-27 20:49:16.363] FSpell (724) x11
2: L [2024-03-27 20:49:16.364] Remove Big Guy on queue
2: L [2024-03-27 20:49:16.364] Found x11 Freeze
2: L [2024-03-27 20:49:16.365]   - Removing x11 queued Freeze

**Comment by MassXXL** [comment]
xbebenk
Is there anything else I need to provide to help resolve this issue?  For some odd reason it loops on TH16s.  Others are not impacted.

**Comment by xbebenk** [comment]
seem this is OCR issue with queued freeze, bot read 1 freeze as 11 freeze
workaround: 
try to change spell composition, maybe with 3 freeze

**Comment by MassXXL** [comment]
Thank you for fixing the issue.
