### ISSUE TITLE
New DonateCC doesn't work!

### ISSUE THREAD

**Issue by benhayes36** [xbebenk/MBR_xbebenkMod#173]
xbebenk

The new DonateCC routine is pretty much broken.  The system from what I see checks for a red icon.  If this doesn't exist, then the bot doesn't go into the clan chat.  This is good on in thought but when you run shared prefs, this doesn't show up red even when there is requests that the bot can donate to.  Below is a screenshot of the bot not going into clan chat but the picture clearly shows donations that it can donate to.

![Donation issue](https://github.com/xbebenk/MBR_xbebenkMod/assets/35671084/4cbb5947-291b-48a5-99ba-425977aacf89)

**Comment by xbebenk** [comment]
there is no new request, the existing request was already seen by this account, hence the red icon not shown

you can edit yourself to disable this red icon check, go to donatecc.au3 
line 169:
![image](https://github.com/xbebenk/MBR_xbebenkMod/assets/6594360/b087afbb-3e35-4c77-a41f-a0c339dba416)
comment out these lines, save
restart bot

**Comment by benhayes36** [comment]
Thanks for this xbebenk.  I'll make the change a bit later and test this out.  Just know that the way you have this implemented is flawed (and I'll explain).  If an account/bot see's red and goes to donate but cannot fill the request due to not having enough troops or spells, the bot will come out of the clan chat.  But the way you have this implemented, the bot will not go back into clan chat even when there are requests to be filled.  As I said, on paper this looks good but in design/implementation, it is flawed.

**Comment by xbebenk** [comment]
thanks, I realize it, commented out and commited
