### ISSUE TITLE
Switch between bases is not working correctly

### ISSUE THREAD

**Issue by KonstantinOsipov** [xbebenk/MBR_xbebenkMod#58]
Switch between bases is not working correctly. 
(Using the latest version)
![image](https://user-images.githubusercontent.com/49527328/172098774-726f33c9-099e-4f84-8bd1-f3445aa947d2.png)

**Comment by xbebenk** [comment]
can you inform what screen on emu? or zoom level or village position?

**Comment by xbebenk** [comment]
or find an image on your profile folder/temp/debug/switchbetweenbases/

**Comment by KonstantinOsipov** [comment]
let me check, I will provide this information.

**Comment by NothingJustBlank** [comment]
Hi @KonstantinOsipov, can you redownload the latest commit from Dev Branch. There are some changes that will allow the bot to automatically save a debug image if this error happens again. Thanks!

**Comment by KonstantinOsipov** [comment]
pulling, and restart.

**Comment by KonstantinOsipov** [comment]
I pulled from dev_1.2.3 And everything works fine. There is no such issue at any of my accounts. Thanks for your support. 
(I will try to test deeply, to find something more serious ))) ). Issue could be closed.
Thx again!
