### ISSUE TITLE
Fatal Aplication exit. Spell Challenges BB

### ISSUE THREAD

**Issue by devreagi** [xbebenk/MBR_xbebenkMod#6]
Hi, this exception occur in builder base during the attack. I'm use daily development version.

![error_bb](https://user-images.githubusercontent.com/69402757/142743897-ff4e61e6-bf07-4c3b-bf85-ab65c73a8c83.png)

This is the builder base config:

![config1_bb](https://user-images.githubusercontent.com/69402757/142743913-3dae5184-8018-40ba-87be-82dd91218480.png)

![config2_bb](https://user-images.githubusercontent.com/69402757/142743910-ff7600a1-7d13-4b1e-a377-4438c52a0bab.png)

**Comment by NothingJustBlank** [comment]
Known issue, BB CSV is not fully imported yet. Please don't use BB CSV, use standard attack. 

Thanks.
