### ISSUE TITLE
Remaining Hero time

### ISSUE THREAD

**Issue by krendll** [xbebenk/MBR_xbebenkMod#63]
Try to fix this "Remaining King recover time: 0.00". It happens if hero has less than 1 minute recover, and bot will not return for him. I think just add a 30 sec pause and reread remaining time would be nice (it could happen twice, not a problem). My dirty hack was to add minute to any hero remaining time, but it is no so correct.
Also please add checkbox not to clean army/spells if user don't want it at all.
Thank You.

**Comment by xbebenk** [comment]
![image](https://user-images.githubusercontent.com/6594360/177008723-429a8ca2-100d-4bb6-b9fd-b9167e171888.png)
