### ISSUE TITLE
Manual hero locate

### ISSUE THREAD

**Issue by Flachaa** [xbebenk/MBR_xbebenkMod#69]
dev 123
Hi. When click on manual locate any hero bot just do nothing. It's working few updates ago. Can you check this Xbebenk or Jason please 
<3

https://imgur.com/a/skZTwiI

**Comment by Flachaa** [comment]
just swap with file from main branch and it's working :)

**Comment by NothingJustBlank** [comment]
Manual hero locate is depracated.
