### ISSUE TITLE
TH 13-14 no train balloons

### ISSUE THREAD

**Issue by devreagi** [xbebenk/MBR_xbebenkMod#7]
Hi, in the latest version (commit **78c4840**) th13-14 not train balloons troops, but my TH from level 11 down yes.

Memu 7.2.9 android 4.4.4 and android 5.1
Troops combiantion: 6 edrag - 4 Healer - 11 ballons - 2 wallbreaker.

screenshot army window:

![noballoon](https://user-images.githubusercontent.com/69402757/142745746-42150a92-afe2-4c88-b267-6b50c1aa31bc.png)

**Log details**

[2021-11-20_20.02.32.log](https://github.com/xbebenk/MBR_xbebenkMod/files/7575615/2021-11-20_20.02.32.log)

**Comment by NothingJustBlank** [comment]
Please test the latest commit.

Thanks.

**Comment by xbebenk** [comment]
resolved on commit
https://github.com/xbebenk/MBR_xbebenkMod/commit/4710750b1663fff99e2fa55da8761512303304b7
