### ISSUE TITLE
Builder base deployment issue

### ISSUE THREAD

**Issue by UsernameLuxi** [xbebenk/MBR_xbebenkMod#86]
Hello there!

I have an issue with the builder base attack feature. One of the images below shows that it deploys x2 barbs when the army camp has x20 capacity. It also tries to deploy x111 barbarians for some reason. Another not as big of an issue is that it tries to place units in the red area quite a lot.
The account is running in BH9.

![billede](https://user-images.githubusercontent.com/94841588/197838414-66d59906-54b4-4e9a-a546-169e86154e67.png)
![billede](https://user-images.githubusercontent.com/94841588/197838570-a2906b15-f90e-4030-9ccc-3437aec1840b.png)

**Comment by xbebenk** [comment]
you need to enable ocr debug to check bot can read 20 properly or no
![image](https://user-images.githubusercontent.com/6594360/198201487-f7df6893-c4f6-4fda-bfb4-9023c90056e7.png)

go attack a base, wait until battle ready and run function : AttackBB() 
wait until bot finish deploying trops, then hit escape on keyboard

go to bot_folder/lib/debug/ocr/ you can review the png file and txt file with same name

**Comment by UsernameLuxi** [comment]
Thank you so much for trying to help.

There's a few pictures where the number 2 is too much cut off perhaps, and therefore it returns 0 in the following pictures:
![ocr_20221028162857_coc-t-s_10](https://user-images.githubusercontent.com/94841588/198646416-17dfa4d8-263d-4925-8c65-92a44f695570.png)
![ocr_20221028162857_coc-t-s](https://user-images.githubusercontent.com/94841588/198646773-88a98998-b560-4d18-8605-b6229fe46b46.png)
![ocr_20221028162857_coc-t-s_4](https://user-images.githubusercontent.com/94841588/198646881-3487eed9-330b-48f1-b287-1a9ade5112b1.png)

**Comment by UsernameLuxi** [comment]
The picture below it reads as 20, which is good, but it's confused about most of them.

![ocr_20221028162857_coc-t-s_2](https://user-images.githubusercontent.com/94841588/198647232-a1b70d20-2d53-4ab9-8707-ccdde1366d70.png)

**Comment by xbebenk** [comment]
please use 1.2.4
![image](https://user-images.githubusercontent.com/6594360/198665882-dd0e9021-cfa2-41ea-b871-7399215eaf1f.png)
sorry i dont have maxed barb, so cannot test 20 space

**Comment by xbebenk** [comment]
use GetAttackBarBB() to produce result

**Comment by UsernameLuxi** [comment]
How do I get 1.2.4?
![billede](https://user-images.githubusercontent.com/94841588/198673096-01405766-0a94-4535-9120-6ba9b854f262.png)

**Comment by xbebenk** [comment]
https://github.com/xbebenk/MBR_xbebenkMod/tree/dev_1.2.4

**Comment by UsernameLuxi** [comment]
Ok great! I tested with the new version, and it looks like it's working. Thank you.
![billede](https://user-images.githubusercontent.com/94841588/198674145-66b05a8c-c274-46f5-aab5-94ed71def4ca.png)

**Comment by xbebenk** [comment]
great!!!
