### ISSUE TITLE
1 suggestion and 1 issue

### ISSUE THREAD

**Issue by TwelveExit** [xbebenk/MBR_xbebenkMod#94]
hey, thanks for your great efforts,

these are more of a suggestion rather than issue,

1. In Attack Plan -> Train Army -> Sieges 
the place of Wall Wrecker and Battle Blimp should be changed because Wall Wrecker is the first siege and Battle Blimp is the 2nd siege when we unlock sieges, but in bot it is displaying the opposite.

2. In Village -> Upgrade -> laboratory -> use book of spell/fight/everything, if lab is more than X days.
when I change X which is the number of days and the bot changes accounts, then I return to that same account but the X days is reset to default values.

Best Regards,

**Comment by xbebenk** [comment]
Thanks for suggestion and report, please check latest commit

**Comment by xbebenk** [comment]
no further comment, i guess it solved
