### ISSUE TITLE
donate troops for daily donations, 1 suggestion

### ISSUE THREAD

**Issue by Pradotec** [xbebenk/MBR_xbebenkMod#95]
hello, thanks for all,

Add task for daily donations for when daily donation are finished stop donate
And enable 1 emerald donate 

Thank you !
Best Regards,

**Comment by xbebenk** [comment]
for daily donation, you can use donation schedule. no need new task
1 gem donation, no i cant add it. however if it added to official, mod will have it

**Comment by Pradotec** [comment]
Thank you !
