### ISSUE TITLE
Troop Train issue 

### ISSUE THREAD

**Issue by smbridges91** [xbebenk/MBR_xbebenkMod#96]
2/5 of my TH6 accounts are unable to train troops.
All 5 accounts have the same settings, but they will open the army tab and see it needs troops, open the training tab and then closes it out and repeat the cycle over and over.

Happened on 1.2.4 and 1.2.3

Please let me know what information you'd like to know.

 [Screenshot ](https://imgur.com/a/qCiBmUr)

**Comment by xbebenk** [comment]
for low TH, try enable double train and misc mod -> ignore bad troop combo, select your troop to fill
